controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home_redirect:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_dashboard  # nom de la route cible (exemple)
    permanent: true       # true pour un code 301, false pour 302
